enum ACTIONS {
    SET_ARTIST = 'SET_ARTIST',
    SET_ALBUMS = 'SET_ALBUMS',
    SET_SEARCH_TEXT = 'SET_SEARCH_TEXT',
    SET_SUGGESTIONS = 'SET_SUGGESTIONS',
    SET_LOADING_ARTIST = 'SET_LOADING_ARTIST',
    UNSET_LOADING_ARTIST = 'UNSET_LOADING_ARTIST',
    SET_LOADING_SUGGESTION = 'SET_LOADING_SUGGESTION',
    UNSET_LOADING_SUGGESTION = 'UNSET_LOADING_SUGGESTION',
    GET_ARTIST_DETAILS = 'GET_ARTIST_DETAILS',
    SET_FEATURED = 'SET_FEATURED',
    GET_FEATURED = 'GET_FEATURED'
}

export default ACTIONS

