enum ACTIONS {
    SET_ARTIST = 'SET_ARTIST',
    SET_ALBUMS = 'SET_ALBUMS',
    SET_SEARCH_TEXT = 'SET_SEARCH_TEXT',
    SET_SUGGESTIONS = 'SET_SUGGESTIONS',
    SET_LOADING_ARTIST = 'SET_LOADING_ARTIST',
    UNSET_LOADING_ARTIST = 'UNSET_LOADING_ARTIST',
    GET_ARTIST_DETAILS = 'GET_ARTIST_DETAILS'
}

export default ACTIONS

